"""empty message

Revision ID: e5276aa0f7e0
Revises: 
Create Date: 2020-02-01 12:43:56.309051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5276aa0f7e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hoteis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=True),
    sa.Column('estrelas', sa.Float(precision=1), nullable=True),
    sa.Column('diaria', sa.Float(precision=2), nullable=True),
    sa.Column('cidade', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hoteis')
    # ### end Alembic commands ###
